/*
 * Horoscope API Documentation
 * ## Indexer for multiple Cosmos Network   ### How to use  Select server Horoscope if use Horoscope API  Select server LCD if use Legacy API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.1.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";
import { randomItem, randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

// const BASE_URL = "https://indexer.dev.aurascan.io/api";
const BASE_URL = "https://indexer-test.dev.aurascan.io/api";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.
// const CHAIN_ID = "euphoria-1"
const CHAIN_ID = "serenity-testnet-001"
const PAGE_LIMIT = "100"
const PAGE_OFFSET = "1"
const CONTRACT_TYPE = "CW721"
const address = JSON.parse(open("./data/account_serenity.json"));
const validator_status = JSON.parse(open("./data/validator_status.json"));
const module = JSON.parse(open("./data/module.json"));
const contractAddressList = JSON.parse(open("./data/contract.json"));

export const options = {
    // vus: 10,
    // iterations: 10,
    stages: [
        { target: 100, duration: '5s' },
        { target: 150, duration: '10s' },
        { target: 200, duration: '15s' },
        { target: 250, duration: '20s' },
        { target: 300, duration: '25s' },
      ],
};

export default function () {
    group("/v1/account-info/delegations", () => {
        const randomAddress = randomItem(address);
        let chainId = CHAIN_ID; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/account-info/delegations?address=${randomAddress}&chainId=${chainId}`;
            let request = http.get(url);

            // console.log(randomAddress);
            // console.log(request);
            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });


    group("/v1/validator", () => {
        let pageLimit = PAGE_LIMIT; // 
        let chainid = CHAIN_ID; // 
        let pageOffset = PAGE_OFFSET; // 
        let operatorAddress = ''; // 
        let nextKey = ''; // 
        let status = randomItem(validator_status);

        // Request No. 1
        {
            let url = BASE_URL + `/v1/validator?chainid=${chainid}&operatorAddress=${operatorAddress}&status=${status}&pageLimit=${pageLimit}&pageOffset=${pageOffset}&nextKey=${nextKey}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/account-info", () => {
        let rdAddress = randomItem(address); // 
        let chainId = CHAIN_ID; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/account-info?address=${rdAddress}&chainId=${chainId}`;
            let request = http.get(url);

            check(request, {
                "Register result": (r) => r.status === 200
            });
        }
    });

    group("/v1/account-unbonds", () => {
        let rdAddress = randomItem(address); // 
        let chainid = CHAIN_ID; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/account-unbonds?chainid=${chainid}&address=${rdAddress}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/transaction", () => {
        let rdAddress = randomItem(address); // 
        let searchType = ''; // 
        let query = ''; // 
        let searchKey = ''; // 
        let reverse = 'true'; // 
        let pageLimit = PAGE_LIMIT; // 
        let blockHeight = ''; // 
        let chainid = CHAIN_ID; // 
        let pageOffset = ''; // 
        let countTotal = 'true'; // 
        let nextKey = ''; // 
        let txHash = ''; // 
        let searchValue = ''; // 
        let addressInContract = ''; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/transaction?chainid=${chainid}`;
            if (rdAddress != '') {
                url = url + `&address=${rdAddress}`;
            }
            if (searchType != '') {
                url = url + `&searchType=${searchType}`;
            }
            if (blockHeight != '') {
                url = url + `&blockHeight=${blockHeight}`;
            }
            if (txHash != '') {
                url = url + `&txHash=${txHash}`;
            }
            if (addressInContract != '') {
                url = url + `&addressInContract=${addressInContract}`;
            }
            if (searchKey != '') {
                url = url + `&searchKey=${searchKey}`;
            }
            if (searchValue != '') {
                url = url + `&searchValue=${searchValue}`;
            }
            if (query != '') {
                url = url + `&query=${query}`;
            }
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (countTotal != '') {
                url = url + `&countTotal=${countTotal}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (reverse != '') {
                url = url + `&reverse=${reverse}`;
            }
            let request = http.get(url);
            // console.log(request);
            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/network/status", () => {
        let chainid = CHAIN_ID; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/network/status?chainid=${chainid}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/proposal", () => {
        let pageLimit = '20'; // 
        let chainid = CHAIN_ID; // 
        let pageOffset = ''; // 
        let nextKey = ''; // 
        let reverse = 'true'; // 
        let proposalId = randomIntBetween(1,20); // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/proposal?chainid=${chainid}`;
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (reverse != '') {
                url = url + `&reverse=${reverse}`;
            }
            if (proposalId != '') {
                url = url + `&proposalId=${proposalId}`;
            }

            let request = http.get(url);

            // console.log(request);
            check(request, {
                "Register result": (r) => r.status === 200
            });
        }
    });

    group("/v1/param", () => {
        let pageLimit = '20'; // 
        let chainid = CHAIN_ID; // 
        let rdModule = randomItem(module); // 
        let pageOffset = ''; // 
        let nextKey = ''; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/param?chainid=${chainid}`;
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (rdModule != '') {
                url = url + `&module=${rdModule}`;
            }

            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/transaction/power-event", () => {
        let pageLimit = '20'; // 
        let rdAddress = randomItem(address); // 
        let chainid = CHAIN_ID; // 
        let pageOffset = ''; // 
        let countTotal = 'true'; // 
        let nextKey = ''; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/transaction/power-event?chainid=${chainid}`;
            if (rdAddress != '') {
                url = url + `&address=${rdAddress}`;
            }
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (countTotal != '') {
                url = url + `&countTotal=${countTotal}`;
            }
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/asset/getByOwner", () => {
        let owner = randomItem(address); // 
        let tokenId = ''; // 
        let chainid = CHAIN_ID; // 
        let tokenName = ''; // 
        let contractAddress = randomItem(contractAddressList); // 
        let countTotal = 'true'; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/asset/getByOwner?owner=${owner}&chainid=${chainid}`;
            if (tokenId != '') {
                url = url + `&tokenId=${tokenId}`;
            }
            if (tokenName != '') {
                url = url + `&tokenName=${tokenName}`;
            }
            if (contractAddress != '') {
                url = url + `&contractAddress=${contractAddress}`;
            }
            if (countTotal != '') {
                url = url + `&countTotal=${countTotal}`;
            }
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/asset/getByContractType", () => {
        let pageLimit = '20'; // 
        let chainid = CHAIN_ID; // 
        let contractType = CONTRACT_TYPE; // 
        let pageOffset = ''; // 
        let countTotal = 'true'; // 
        let nextKey = ''; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/asset/getByContractType?contractType=${contractType}&chainid=${chainid}`;
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (countTotal != '') {
                url = url + `&countTotal=${countTotal}`;
            }
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/asset/holder", () => {
        let pageLimit = '20'; // 
        let chainid = CHAIN_ID; // 
        let contractType = CONTRACT_TYPE; // 
        let pageOffset = ''; // 
        let contractAddress  = randomItem(contractAddressList); // 
        let countTotal = 'true'; // 
        let nextKey = ''; // 
        let reverse = 'true'; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/asset/holder?chainid=${chainid}`;
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (countTotal != '') {
                url = url + `&countTotal=${countTotal}`;
            }
            if (contractType != '') {
                url = url + `&contractType=${contractType}`;
            }
            if (contractAddress != '') {
                url = url + `&contractAddress=${contractAddress}`;
            }
            if (reverse != '') {
                url = url + `&reverse=${reverse}`;
            }
            let request = http.get(url);
            // console.log(request);
            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    //***********WIP********************************
    //     group("/v1/validator/delegator-reward-claimed", () => {
    //         let chainid = CHAIN_ID; // 
    //         let validatorAddress = 'aura1rl45t75hv8jz0qjsem27g2a4m2xlndq4ewcm25'; // 
    //         let delegatorAddress = randomItem(address); // 

    //         // Request No. 1
    //         {
    //             let url = BASE_URL + `/v1/validator/delegator-reward-claimed?chainid=${chainid}&delegatorAddress=${delegatorAddress}&validatorAddress=${validatorAddress}`;
    //             let request = http.get(url);
    // console.log(request);
    //             check(request, {
    //                 "OK": (r) => r.status === 200
    //             });
    //         }
    //     });
    //*******************************************

    group("/v1/asset/index", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/v1/asset/index`;
            // TODO: edit the parameters of the request body.
            let body = { "codeId": randomIntBetween(1, 379), "contractType": "CW721", "chainId": CHAIN_ID };
            let params = { headers: { "Content-Type": "application/json", "Accept": "application/json" } };
            let request = http.post(url, JSON.stringify(body), params);
            // console.log(JSON.stringify(request).toString());
            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/v1/block", () => {
        let blockHash = ''; // 
        let pageLimit = '20'; // 
        let blockHeight = ''; // 
        let consensusHexAddress = ''; // 
        let chainid = CHAIN_ID; // 
        let pageOffset = ''; // 
        let operatorAddress = ''; // 
        let countTotal = 'true'; // 
        let nextKey = ''; // 
        let reverse = 'true'; // 

        // Request No. 1
        {
            let url = BASE_URL + `/v1/block?chainid=${chainid}`;
            if (pageOffset != '') {
                url = url + `&pageOffset=${pageOffset}`;
            }
            if (pageLimit != '') {
                url = url + `&pageLimit=${pageLimit}`;
            }
            if (nextKey != '') {
                url = url + `&nextKey=${nextKey}`;
            }
            if (countTotal != '') {
                url = url + `&countTotal=${countTotal}`;
            }
            if (blockHash != '') {
                url = url + `&blockHash=${blockHash}`;
            }
            if (blockHeight != '') {
                url = url + `&blockHeight=${blockHeight}`;
            }
            if (reverse != '') {
                url = url + `&reverse=${reverse}`;
            }
            if (consensusHexAddress != '') {
                url = url + `&consensusHexAddress=${consensusHexAddress}`;
            }
            if (operatorAddress != '') {
                url = url + `&operatorAddress=${operatorAddress}`;
            }
            let request = http.get(url);

            check(request, {
                "Block result": (r) => r.status === 200
            });
        }
    });

}
