name: Continuous integration

on:
  push:
    branches: [main, develop, staging, test-performance]

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit
  build:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     registry-url: https://npm.pkg.github.com/aura-nw
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)"  >> $GITHUB_OUTPUT  
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/aura-indexer-crawl:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
      - name: Build the Docker image and push it to the registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.KEY_NPM_RC }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          chmod 777 -R ./ci
          ./ci/build.sh
  updateManifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@v2
      - name: Set environment variable
        run: |
          SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
          echo CONTAINER_RELEASE_IMAGE=ghcr.io/aura-nw/aura-indexer-crawl:${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
          echo REPO_MANIFEST_NAME=gitops >> $GITHUB_ENV
          echo REPO_MANIFEST_URL=github.com/aura-nw/gitops.git >> $GITHUB_ENV
          echo REPO_MANIFEST_BRANCH=master >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev/horoscope/horoscope-crawl-auratestnet >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_TEST_PERFORMANCE=./clusters/k8s-dev/indexer-load-test >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_STAGING=./clusters/k8s-testnet-euphoria/horoscope/horoscope-crawl-serenity >> $GITHUB_ENV
          echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-prod/horoscope/horoscope-crawl-euphoria >> $GITHUB_ENV
          echo REPO_MANIFEST_TAG_IMAGE=image_aura_indexer_crawl >> $GITHUB_ENV
      - name: Update manifest
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          chmod 777 -R ./ci
          ./ci/updateManifest.sh
