name: Continuous integration for feegrant

on:
  push:
    branches: [feegrant]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        env:
          REDIS_USERNAME: default
          NODE_ENV: test
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 123456
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install typescript
        run: npm install typescript
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build --if-present
      - name: Run test
        run: npm run test